site_name: LineageTree documentation
theme:
  name: material
  features:
  - navigation.path
  - navigation.expand
  - content.code.annotate
plugins:
- mkdocstrings:
    handlers:
      python:
        options:
          show_submodules: true
          docstring_style: numpy
nav:
  - Home: index.md
  - Getting started:
    - Download and Import: getting-started.md
    - Glossary: glossary.md
    - Loaders: loaders.md
    - Visualization: viz.md
    - Uted: uted.md
  - API Reference: api.md
