site_name: LineageTree documentation
theme:
  name: material
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  features:
  - navigation.path
  - navigation.expand
  - content.code.annotate
markdown_extensions:
  - toc:
      permalink: true
  - tables
  - pymdownx.superfences   
plugins:
- mkdocstrings:
    handlers:
      python:
        setup_commands:
            - import os, sys
            - sys.path.append(os.path.abspath("._io"))
        options:
          docstring_style: numpy
          
nav:
  - Home: index.md
  - Getting started:
    - Download and Import: getting-started.md
    - Glossary: glossary.md
  - Loaders: loaders.md
  - Visualization: viz.md
  - Uted: uted.md
  - API Reference: api.md
